version: '3.9'
services:
  product-db:
    container_name: product-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product-service
    ports:
      - '6000:6000'
    volumes:
      - pgdata1:/var/lib/postgresql/data

  product-service:
    container_name: product-service
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      DB_SCHEMA: product-service
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: product-db

    depends_on:
      - product-db
    ports:
      - '3001:3001'

volumes:
  pgdata1: {}

networks:
    default:
        external:
            name: ecommerce-build
